### ISSUE TITLE
Song playing over and over

### ISSUE THREAD

**Issue by CringyAdam** [CringyAdam/CringyBot#1]
I would like some of my contributors who do a good job to tell me why the last queued song is playing over and over again till I stop it as I'm bad with `ytdl-core` and queuing systems.

Thanks in advance.

**Comment by Haxmat** [comment]
thats not an issue with ytdl-core thats an issue with the way your queue is setup

**Comment by CringyAdam** [comment]
@Haxmat Can you help me with that please I do not remember what I did there.

**Comment by HTMLisNOTprogramming** [comment]
why u so gey m9
